name:                server
version:             0.1.0.0
github:              "githubuser/server"
license:             BSD3
author:              "Author name here"
maintainer:          "example@example.com"
copyright:           "2022 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/server#readme>

dependencies:
- base >=4.14.2.0
- aeson
- bytestring
- containers
- cryptonite
- directory
- exceptions
- extra
- file-embed
- generic-lens
- http-types
- memory
- monad-control
- mtl
- postgresql-simple
- postgresql-simple-migration 
- random
- resource-pool
- text
- time
- wai
- wai-extra
- warp

- hspec
- QuickCheck

default-extensions:
- AllowAmbiguousTypes
- ConstraintKinds
- DataKinds
- DefaultSignatures
- DeriveAnyClass
- DeriveFunctor 
- DeriveGeneric
- DerivingStrategies
- DerivingVia
- ExistentialQuantification
- FlexibleContexts
- FlexibleInstances
- ImplicitParams
- ImportQualifiedPost
- LambdaCase
- MultiParamTypeClasses
- OverloadedLabels
- OverloadedStrings
- RankNTypes
- RecordWildCards
- ScopedTypeVariables
- StandaloneDeriving
- TypeApplications
- TypeFamilies
- TypeOperators
- UndecidableInstances

ghc-options: 
  -j6
  -O0

library:
  source-dirs: src

executables:
  server-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    - -Werror
    - -Wno-unused-do-bind
    #- -Wno-unused-imports
    - -Wno-unused-matches
    - -Wno-unused-foralls
    - -Wno-unused-local-binds
    dependencies:
    - server

tests:
  server-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - server
